imports:
    - { resource: config.yml }

doctrine:
    dbal:
        url: "%database_url%"
        driver: pdo_pgsql
        host: '%database_host_heroku%'
        port: '%database_port_heroku%'
        dbname: '%database_name_heroku%'
        user: '%database_user_heroku%'
        password: '%database_password_heroku%'
        charset: UTF8
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type: fingers_crossed
#            action_level: error
            action_level: %monolog_action_level%
            handler: nested
        nested:
            type: stream
            path: "php://stderr"
#            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
        console:
            type: console
            process_psr_3_messages: false
